"""quiz_sessions streak to correct_count

Revision ID: 05113a8f1bbe
Revises: 7d086c44c0e6
Create Date: 2026-08-07 17:47:08.113746
"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '05113a8f1bbe'
down_revision: str | None = '7d086c44c0e6'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('quiz_sessions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('correct_count', sa.Integer(), nullable=False))
        batch_op.drop_column('streak')

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('quiz_sessions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('streak', sa.INTEGER(), nullable=False))
        batch_op.drop_column('correct_count')

    # ### end Alembic commands ###
