"""add shipping snapshot to orders

Revision ID: fed0b073f678
Revises: 05113a8f1bbe
Create Date: 2026-08-21 18:49:31.667501
"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fed0b073f678'
down_revision: str | None = '05113a8f1bbe'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.add_column(sa.Column('ship_name', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('ship_line1', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('ship_line2', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('ship_city', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('ship_region', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('ship_postal', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('ship_country', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.drop_column('ship_country')
        batch_op.drop_column('ship_postal')
        batch_op.drop_column('ship_region')
        batch_op.drop_column('ship_city')
        batch_op.drop_column('ship_line2')
        batch_op.drop_column('ship_line1')
        batch_op.drop_column('ship_name')

    # ### end Alembic commands ###
